import type { Provider } from './store'

export const categories = [
  { id: 'massage', name: 'Massage', cebuano: 'Massage', icon: 'Heart' },
  { id: 'carpentry', name: 'Carpentry', cebuano: 'Panday', icon: 'Hammer' },
  { id: 'cleaning', name: 'Cleaning', cebuano: 'Limpyo balay', icon: 'Sparkles' },
  { id: 'repairs', name: 'Repairs', cebuano: 'Ayuhon', icon: 'Wrench' },
] as const

export const providers: Record<string, Provider[]> = {
  massage: [
    {
      id: 'm1',
      name: 'Maria Santos',
      category: 'massage',
      location: 'Lahug, Cebu City',
      priceRange: '\u20B1400 \u2013 \u20B11,200',
      rating: 4.9,
      image: '/images/provider-maria.jpg',
      verified: true,
      availableToday: true,
      popular: true,
      description: 'Professional massage therapist with 8 years experience. Specializes in hilot, Swedish, and deep tissue massage. Home service available within Cebu City.',
      responseTime: '< 10 min',
      bookings: '500+',
      memberSince: '2021',
      reviews: [
        { text: 'Maayo kaayo si Maria! Professional og relaxing ang massage.', author: 'Joy, Lahug', rating: 5 },
        { text: 'The best hilot experience I\'ve had. Highly recommended!', author: 'Mark, IT Park', rating: 5 },
      ],
    },
    {
      id: 'm2',
      name: 'Jenny Cruz',
      category: 'massage',
      location: 'IT Park, Cebu City',
      priceRange: '\u20B1500 \u2013 \u20B11,500',
      rating: 4.8,
      image: '/images/provider-jenny.jpg',
      verified: true,
      availableToday: true,
      popular: false,
      description: 'Licensed massage therapist specializing in Swedish and hot stone therapy. Available for hotel and home service bookings.',
      responseTime: '< 15 min',
      bookings: '350+',
      memberSince: '2022',
      reviews: [
        { text: 'Very professional and accommodating. Great for office workers!', author: 'Anna, Cebu Business Park', rating: 5 },
        { text: 'Jenny knows exactly where the tension is. Will book again.', author: 'Carlo, Mabolo', rating: 4 },
      ],
    },
    {
      id: 'm3',
      name: 'Ana Reyes',
      category: 'massage',
      location: 'Talamban, Cebu City',
      priceRange: '\u20B1350 \u2013 \u20B11,000',
      rating: 4.7,
      image: '/images/provider-ana.jpg',
      verified: true,
      availableToday: false,
      popular: false,
      description: 'Traditional hilot practitioner with training in modern massage techniques. Affordable rates with quality service guaranteed.',
      responseTime: '< 20 min',
      bookings: '200+',
      memberSince: '2023',
      reviews: [
        { text: 'Very affordable but high quality. Ana is so friendly too!', author: 'Mia, Talamban', rating: 5 },
      ],
    },
    {
      id: 'm4',
      name: 'Rosa Bautista',
      category: 'massage',
      location: 'Banilad, Cebu City',
      priceRange: '\u20B1450 \u2013 \u20B11,300',
      rating: 4.9,
      image: '/images/provider-maria.jpg',
      verified: true,
      availableToday: true,
      popular: true,
      description: 'Expert in therapeutic massage and reflexology. Over 10 years of experience serving clients in Cebu.',
      responseTime: '< 10 min',
      bookings: '800+',
      memberSince: '2020',
      reviews: [
        { text: 'Rosa is a true professional. My back pain is gone!', author: 'Dennis, Banilad', rating: 5 },
        { text: 'The reflexology session was amazing. Worth every peso.', author: 'Liza, Mabolo', rating: 5 },
      ],
    },
    {
      id: 'm5',
      name: 'Liza Tan',
      category: 'massage',
      location: 'Mabolo, Cebu City',
      priceRange: '\u20B1300 \u2013 \u20B1900',
      rating: 4.6,
      image: '/images/provider-jenny.jpg',
      verified: true,
      availableToday: false,
      popular: false,
      description: 'New but highly rated massage therapist. Offers a variety of massage styles at budget-friendly prices.',
      responseTime: '< 30 min',
      bookings: '100+',
      memberSince: '2024',
      reviews: [
        { text: 'Great value for money. Liza is very attentive.', author: 'Ryan, Mabolo', rating: 4 },
      ],
    },
  ],
  carpentry: [
    {
      id: 'c1',
      name: 'Boyet dela Cruz',
      category: 'carpentry',
      location: 'Lahug, Cebu City',
      priceRange: '\u20B1500 \u2013 \u20B12,000',
      rating: 4.8,
      image: '/images/provider-boyet.jpg',
      verified: true,
      availableToday: true,
      popular: false,
      description: 'Master carpenter with 15 years of experience. Custom furniture, cabinets, home repairs, and renovation work.',
      responseTime: '< 15 min',
      bookings: '400+',
      memberSince: '2021',
      reviews: [
        { text: 'Boyet built our kitchen cabinets. Excellent craftsmanship!', author: 'Sarah, Lahug', rating: 5 },
        { text: 'Reliable and always on time. Fair pricing too.', author: 'Juan, Banilad', rating: 4 },
      ],
    },
    {
      id: 'c2',
      name: 'Mang Jun Almario',
      category: 'carpentry',
      location: 'Talamban, Cebu City',
      priceRange: '\u20B1400 \u2013 \u20B11,500',
      rating: 4.9,
      image: '/images/provider-mangjun.jpg',
      verified: true,
      availableToday: false,
      popular: true,
      description: 'Veteran carpenter specializing in traditional Filipino woodworking and modern furniture making.',
      responseTime: '< 10 min',
      bookings: '600+',
      memberSince: '2020',
      reviews: [
        { text: 'Mang Jun is a true artisan. His work is beautiful.', author: 'Celia, Talamban', rating: 5 },
        { text: 'Repaired our dining table like new. Very skilled!', author: 'Pedro, Lahug', rating: 5 },
      ],
    },
    {
      id: 'c3',
      name: 'Dodong Ferrer',
      category: 'carpentry',
      location: 'Banilad, Cebu City',
      priceRange: '\u20B1350 \u2013 \u20B11,200',
      rating: 4.7,
      image: '/images/provider-boyet.jpg',
      verified: true,
      availableToday: true,
      popular: false,
      description: 'All-around handyman and carpenter. Doors, windows, shelves, and small repairs done quickly.',
      responseTime: '< 20 min',
      bookings: '250+',
      memberSince: '2022',
      reviews: [
        { text: 'Fixed our broken door in under an hour. Great service!', author: 'Tina, Banilad', rating: 4 },
      ],
    },
    {
      id: 'c4',
      name: 'Toto Villanueva',
      category: 'carpentry',
      location: 'Mabolo, Cebu City',
      priceRange: '\u20B1450 \u2013 \u20B11,800',
      rating: 4.8,
      image: '/images/provider-mangjun.jpg',
      verified: true,
      availableToday: false,
      popular: false,
      description: 'Specialist in home renovation and custom carpentry. Quality materials and workmanship guaranteed.',
      responseTime: '< 15 min',
      bookings: '300+',
      memberSince: '2021',
      reviews: [
        { text: 'Toto renovated our living room. Beyond our expectations!', author: 'Grace, Mabolo', rating: 5 },
      ],
    },
    {
      id: 'c5',
      name: 'Noynoy Enriquez',
      category: 'carpentry',
      location: 'Cebu Business Park',
      priceRange: '\u20B1600 \u2013 \u20B12,500',
      rating: 5.0,
      image: '/images/provider-boyet.jpg',
      verified: true,
      availableToday: false,
      popular: true,
      description: 'Premium carpenter for high-end residential and commercial projects. Detailed estimates provided.',
      responseTime: '< 10 min',
      bookings: '450+',
      memberSince: '2020',
      reviews: [
        { text: 'Noynoy built our office reception desk. Absolutely stunning work.', author: 'David, Cebu Business Park', rating: 5 },
        { text: 'The attention to detail is incredible. Worth every peso.', author: 'Rachel, IT Park', rating: 5 },
      ],
    },
  ],
  cleaning: [
    {
      id: 'cl1',
      name: 'Susan Mendoza',
      category: 'cleaning',
      location: 'Lahug, Cebu City',
      priceRange: '\u20B1300 \u2013 \u20B1800',
      rating: 4.8,
      image: '/images/provider-ana.jpg',
      verified: true,
      availableToday: true,
      popular: true,
      description: 'Experienced house cleaner with 6 years of service. Thorough, reliable, and uses eco-friendly products.',
      responseTime: '< 15 min',
      bookings: '450+',
      memberSince: '2021',
      reviews: [
        { text: 'Susan leaves our house spotless every time. Highly recommended!', author: 'Pat, Lahug', rating: 5 },
      ],
    },
    {
      id: 'cl2',
      name: 'Nenita Gako',
      category: 'cleaning',
      location: 'IT Park, Cebu City',
      priceRange: '\u20B1350 \u2013 \u20B1900',
      rating: 4.7,
      image: '/images/provider-maria.jpg',
      verified: true,
      availableToday: true,
      popular: false,
      description: 'Professional condo and apartment cleaning specialist. Perfect for busy professionals.',
      responseTime: '< 20 min',
      bookings: '300+',
      memberSince: '2022',
      reviews: [
        { text: 'Nenita is perfect for our condo. Always thorough and friendly.', author: 'Alex, IT Park', rating: 4 },
      ],
    },
    {
      id: 'cl3',
      name: 'Belen Torres',
      category: 'cleaning',
      location: 'Talamban, Cebu City',
      priceRange: '\u20B1250 \u2013 \u20B1700',
      rating: 4.9,
      image: '/images/provider-jenny.jpg',
      verified: true,
      availableToday: false,
      popular: true,
      description: 'Deep cleaning expert. Post-construction cleaning, move-in/move-out cleaning, and regular maintenance.',
      responseTime: '< 10 min',
      bookings: '350+',
      memberSince: '2022',
      reviews: [
        { text: 'Belen did a deep clean after our renovation. Amazing results!', author: 'Olive, Talamban', rating: 5 },
      ],
    },
    {
      id: 'cl4',
      name: 'Coring Diaz',
      category: 'cleaning',
      location: 'Banilad, Cebu City',
      priceRange: '\u20B1300 \u2013 \u20B1750',
      rating: 4.6,
      image: '/images/provider-ana.jpg',
      verified: true,
      availableToday: true,
      popular: false,
      description: 'Reliable housekeeper for weekly or bi-weekly cleaning. Flexible scheduling available.',
      responseTime: '< 30 min',
      bookings: '200+',
      memberSince: '2023',
      reviews: [
        { text: 'Coring has been cleaning our house weekly for months. Very trustworthy.', author: 'Manny, Banilad', rating: 4 },
      ],
    },
    {
      id: 'cl5',
      name: 'Doring Flores',
      category: 'cleaning',
      location: 'Mabolo, Cebu City',
      priceRange: '\u20B1250 \u2013 \u20B1600',
      rating: 4.8,
      image: '/images/provider-maria.jpg',
      verified: true,
      availableToday: false,
      popular: false,
      description: 'Affordable and efficient cleaning services. Great for apartments and small homes.',
      responseTime: '< 20 min',
      bookings: '150+',
      memberSince: '2023',
      reviews: [
        { text: 'Budget-friendly and does a great job. Highly recommended!', author: 'Ben, Mabolo', rating: 5 },
      ],
    },
  ],
  repairs: [
    {
      id: 'r1',
      name: 'Tony Fernandez',
      category: 'repairs',
      location: 'Lahug, Cebu City',
      priceRange: '\u20B1300 \u2013 \u20B11,500',
      rating: 4.9,
      image: '/images/provider-boyet.jpg',
      verified: true,
      availableToday: true,
      popular: true,
      description: 'All-around repairman. Electrical, plumbing, appliance repair, and general home maintenance.',
      responseTime: '< 10 min',
      bookings: '550+',
      memberSince: '2020',
      reviews: [
        { text: 'Tony fixed our leaking pipe and electrical issue in one visit. Amazing!', author: 'Linda, Lahug', rating: 5 },
      ],
    },
    {
      id: 'r2',
      name: 'Peping Santos',
      category: 'repairs',
      location: 'IT Park, Cebu City',
      priceRange: '\u20B1400 \u2013 \u20B12,000',
      rating: 4.8,
      image: '/images/provider-mangjun.jpg',
      verified: true,
      availableToday: true,
      popular: false,
      description: 'Licensed electrician and plumber. Commercial and residential repairs. Emergency calls accepted.',
      responseTime: '< 15 min',
      bookings: '400+',
      memberSince: '2021',
      reviews: [
        { text: 'Peping responded to our emergency call within 30 minutes. Saved the day!', author: 'Rob, IT Park', rating: 5 },
      ],
    },
    {
      id: 'r3',
      name: 'Enteng Cruz',
      category: 'repairs',
      location: 'Talamban, Cebu City',
      priceRange: '\u20B1250 \u2013 \u20B11,000',
      rating: 4.7,
      image: '/images/provider-boyet.jpg',
      verified: true,
      availableToday: false,
      popular: false,
      description: 'Handyman for all minor repairs. Door locks, switches, faucets, and more. Quick and affordable.',
      responseTime: '< 20 min',
      bookings: '250+',
      memberSince: '2022',
      reviews: [
        { text: 'Enteng fixed everything on our list in just 2 hours. Great value!', author: 'Nita, Talamban', rating: 4 },
      ],
    },
    {
      id: 'r4',
      name: 'Domeng Reyes',
      category: 'repairs',
      location: 'Banilad, Cebu City',
      priceRange: '\u20B1350 \u2013 \u20B11,500',
      rating: 4.8,
      image: '/images/provider-mangjun.jpg',
      verified: true,
      availableToday: true,
      popular: true,
      description: 'Air conditioning and appliance repair specialist. Warranty on all repairs.',
      responseTime: '< 15 min',
      bookings: '380+',
      memberSince: '2021',
      reviews: [
        { text: 'Domeng repaired our AC when 2 other technicians couldn\'t. Expert!', author: 'Karen, Banilad', rating: 5 },
      ],
    },
    {
      id: 'r5',
      name: 'Romy Lim',
      category: 'repairs',
      location: 'Mabolo, Cebu City',
      priceRange: '\u20B1250 \u2013 \u20B1800',
      rating: 4.6,
      image: '/images/provider-boyet.jpg',
      verified: true,
      availableToday: false,
      popular: false,
      description: 'General repair handyman. Honest pricing and quality workmanship on every job.',
      responseTime: '< 25 min',
      bookings: '180+',
      memberSince: '2023',
      reviews: [
        { text: 'Romy is honest and reliable. Fair prices and good work.', author: 'Ella, Mabolo', rating: 4 },
      ],
    },
  ],
}

export function getProvidersByCategory(category: string): Provider[] {
  return providers[category] || []
}
